Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 20, in form_valid
    SignUpView.register_user(form.cleaned_data, self.request)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 43, in register_user
    logger.info(_('Пользователь ') + request.user.get_full_name() + _(' (') + request.user.username + _(') только что зарегистрировался на сайте.'))
TypeError: Can't convert '__proxy__' object to str implicitly
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 20, in form_valid
    SignUpView.register_user(form.cleaned_data, self.request)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 41, in register_user
    logger.info(_('Пользователь ') + form['first_name'] + form['last_name'] + _(' (') + form['username'] + _(') только что зарегистрировался на сайте.'))
TypeError: Can't convert '__proxy__' object to str implicitly
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 20, in form_valid
    SignUpView.register_user(form.cleaned_data, self.request)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 41, in register_user
    logger.info(_('Пользователь ')+str(form['first_name'])+str(form['last_name'])+' ('+str(form['username'])+_(') только что зарегистрировался на сайте.'))
TypeError: Can't convert '__proxy__' object to str implicitly
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 20, in form_valid
    SignUpView.register_user(form.cleaned_data)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/yallen/Документы/Python/Django/DIHT/DIHT/apps/accounts/views.py", line 31, in register_user
    is_active=False)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/models.py", line 187, in create_user
    **extra_fields)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/models.py", line 180, in _create_user
    date_joined=now, **extra_fields)
TypeError: ModelBase object got multiple values for keyword argument 'is_active'
